# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Exercícios aula 8 tuplas

#1 -  Crie uma tupla chamada frutas com pelo menos 5 frutas diferentes. Em seguida, acesse e imprima o terceiro elemento da tupla.

frutas = ('banana', 'maça', 'morango', 'laranja', 'kiwi')
print("A terceira fruta é", frutas[2])

#2 - Crie uma tupla chamada numeros com alguns números inteiros. Em seguida, converta essa tupla em uma lista e imprima a lista resultante.

numeros = {2,5,8,10,25,52,66,99}
numeros2 = list(numeros)
print(numeros2)

#3 - Crie uma tupla chamada meses com os nomes dos meses do ano até Setembro. Use um loop for para imprimir cada mês em uma linha separada.

meses = ('Janeiro','Fevereiro','Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro')
for n in meses:
 print(n)

#4 - Crie uma lista chamada notas com algumas notas de alunos. Em seguida, converta essa lista em uma tupla e imprima a tupla resultante.

notas = [5,10,8,7,6,4,9]
notas2 = tuple(notas)
print(notas2)

#5 - Crie uma lista chamada ponto que represente as coordenadas (x, y) de um ponto. Em seguida, desempacote os elementos da lista em duas variáveis separadas (x e y) e imprima os valores.

pontos = (5,10)
x , y = pontos
print("Coordenada 1 =", x)
print("Coordenada 2 =", y)