# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

contador = 1
while contador <= 25:
 print("Contador:", contador)
 contador +=3

#Exercício 1: Contagem regressiva simples
#Escreva um programa que exiba uma contagem regressiva de 10 a 1, e depois imprima "Fogo!".

contador = 10
while contador > 0:
 print("Número:",contador)
 contador -=1
 if contador == 0:
  print("Fogo!")

#Exercício 4: Números ímpares reversos
#Exiba uma contagem regressiva de números ímpares de 99 a 1.

contador = 99
while contador > 0:
  print("Número:",contador)
  contador -=2