# -*- coding: utf-8 -*-
"""Olá, este é o Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Método Random
# 1 - Crie um número aleatório de 5, 10

import random
x = random.randint(5,10)
print(x)

# 2 - Crie 3 números aleatórios
import random
x = random.randrange(1,30)
y = random.randrange(1,30)
z = random.randrange(1,30)
print(x)
print(y)
print(z)

# 3 - Crie um número aleatório entre 10 e 30 utilize o range()
import random
x = random.randrange(10,30)
print(x)